### ISSUE TITLE
Nextjs Error webpack : TypeError: _builder__WEBPACK_IMPORTED_MODULE_1__.builder.prismaObject

### ISSUE THREAD

**Issue by Robin-Ln** [hayes/pothos#725] opened 2022-12-28 10:25 UTC
### Link to the code that reproduces this issue

https://gitlab.com/Robin-Ln/issue-monorepo-nextjs-prisma-pothos
https://codesandbox.io/p/sandbox/issue-monorepo-nextjs-prisma-pothos-k033nm
### To Reproduce

- clone project 
- install
```
pnpm install
pnpm --filter @packages/database generate
pnpm --filter @apps/app dev
```
- got to http://localhost:3000/api/graphql

### Describe the Bug

```
error - ../packages/graphql/src/schema.ts (5:0) @ builder
error - TypeError: _builder__WEBPACK_IMPORTED_MODULE_1__.builder.prismaObject is not a function
    at eval (webpack-internal:///(api)/../../packages/graphql/src/schema.ts:12:47)
  3 | import { builder } from "./builder";
  4 | 
> 5 | builder.prismaObject("User", {
  6 |   fields: (t) => ({
  7 |     id: t.exposeID("id"),
  8 |   }),
```

### Expected Behavior

show graphql-yoga playground on http://localhost:3000/api/graphql

**Comment by hayes** [comment] 2022-12-28 23:47
Plugins should be imported in the same package that creates the builder.  Re-exporting plugins may cause unexpected behavior due to how pnpm isolates modules. FWIW the repro works correctly for me locally, which is interesting.

In codesandbox this is fixed by chaning the imports slightly:

```ts
// packages/graphql/builder.ts
import SchemaBuilder from "@pothos/core";
import PrismaPlugin from "@pothos/plugin-prisma";
import { db } from "@packages/database";
import type { PrismaTypes } from "@packages/database";

export const builder = new SchemaBuilder<{ PrismaTypes: PrismaTypes }>({
  plugins: [PrismaPlugin],
  prisma: {
    client: db,
  },
});
```

**Closed by hayes** 2022-12-28 23:47 UTC

**Comment by Robin-Ln** [comment] 2022-12-29 11:00
thx for your response @hayes  :)
