### ISSUE TITLE
Indirect prisma relations has type errors.

### ISSUE THREAD

**Issue by charleslai2000** [hayes/pothos#1184] opened 2024-04-07 09:18 UTC
When upgrade to 3.64.0 of @pothos/plugin-prisma, typescript report a type error for every indirect relations. A sample code is below:

```typescript

export const ConceptNode = builder.prismaNode('Concept', {
  description: 'Concept information',
  // https://pothos-graphql.dev/docs/plugins/prisma#select-mode-for-types
  select: { id: true },
  // https://pothos-graphql.dev/docs/plugins/prisma#prismanode
  id: { field: 'id' },
  fields: t => ({
    version: t.exposeString('version', { description: 'Concept version' }),
    type: t.expose('type', {
      description: 'Concept type',
      type: ConceptCategoryEnum,
    }),
    name: t.exposeString('name', { description: 'Concept name' }),
    abbreviation: t.exposeString('abbreviation', { description: 'Concept abbreviation' }),
    description: t.exposeString('description', { description: 'Concept description' }),
    // https://pothos-graphql.dev/docs/plugins/prisma#indirect-relations-eg-join-tables
    superiors: t.field({
      description: 'Superior concepts',
      select: (args, ctx, nestedSelection) => ({
        superiors: {
          select: {
            superior: nestedSelection(true),
          },
        },
      }),
      type: [ConceptNode],
      resolve: concept => concept.superiors.map(({ superior }) => superior),
    }),
  }),
})

```

The select field of superiors field report error: Type '{ superiors: { select: { superior: true; }; }; }' is not assignable to type 'never'.ts(2322)

Please check this. My whole project can not compile now.

**Comment by hayes** [comment] 2024-04-07 16:12
Have you rerun Prisma generate after upgrading?

**Comment by charleslai2000** [comment] 2024-04-13 16:16
Yes, I have re-run the generate command.

**Comment by hayes** [comment] 2024-04-15 22:00
I haven't been able to replicate this in any of the repos I have that use the Prisma plugin.   Is there a reproduction you might be able to share?

**Comment by hayes** [comment] 2024-07-10 16:55
Let me know if you are still having issues, but since Ive been unable to reproduce, and haven't gotten any more info here, I am hoping this has been resolved.  I'm going to close this out for now.

**Closed by hayes** 2024-07-10 16:55 UTC

**Comment by charleslai2000** [comment] 2024-07-16 15:44
The issue is disappeared after I installed the latest version, Thanks.
