### ISSUE TITLE
Add interfaces to Connections and Edges

### ISSUE THREAD

**Issue by Emilios1995** [hayes/pothos#715] opened 2022-12-20 21:14 UTC
Right now it's not possible to add interfaces to the Connection and Edge types created with `t.connection` and `builder.connectionObject`. (The immediate cause seems to be that `ConnectionObjectOptions` extends `ObjectTypeOptions` rather than `ObjectTypeWithInterfaceOptions`, though I'm not sure whether simply changing the type would work.)

Would it be possible support this use case?

**Comment by hayes** [comment] 2022-12-20 21:41
I don't think just changing the type is quite the right solution, but from a runtime perspective, I think this is purely a typing issue.  You can likely pass interfaces as part of the options object and it should work.

The problem is a question of type-safety.  It would be easy to pass an interface that the connection or edge can't actually satisfy safely.  I can look into what it would take to make this work safely.  As a temporary workaround, you can likely pas something like this for the connection/edge options:

```ts
{
  ...({
      interfaces: [SomeInterface]
  } as {})
}
```

**Comment by hayes** [comment] 2022-12-23 23:43
this should be fixed in the latest release

**Closed by hayes** 2022-12-23 23:43 UTC
