### ISSUE TITLE
Prisma generator generate wrong imports when using ESM

### ISSUE THREAD

**Issue by joshuaavalon** [hayes/pothos#1204] opened 2024-05-21 09:13 UTC
Environment:
* Window 10
* Node.JS: v20.10.0
* @pothos/core: 3.41.1
* @pothos/plugin-prisma: 3.65.1

When I use the following options,
```prisma
generator pothos {
  provider = "prisma-pothos-types"
  clientOutput = "@prisma/client"
}
```

It generates the following import statement.
```ts
import type { Prisma } from "@prisma\\client\\index.js";
```

It seems to treat `@prisma/client` as path instead of package name.

**Comment by hayes** [comment] 2024-05-21 15:59
Thanks for reporting this!  Looks like the issue is this line: https://github.com/hayes/pothos/blob/main/packages/plugin-prisma/src/generator.ts#L54

Join will use path seperators based on the OS.  I think the correct thing to do there is to only append index.js if the path doesn't start with `@`, and then use`path.posix.join` instead of `path.join` for this path because it should always use posix style paths.

**Comment by hayes** [comment] 2024-05-21 17:26
should be fixed now!

**Closed as completed by hayes** 2024-05-21 17:26 UTC
