### ISSUE TITLE
[Bug]: Cursor-based pagination skips elements due to incorrect offset from Drizzle plugin

### ISSUE THREAD

**Issue by baristikir** [hayes/pothos#1361] opened 2024-12-26 11:39 UTC
I'm using the Drizzle plugin with Relay integration and am seeing the following issue when performing a cursor-based pagination using the GraphQL Relay nodes, elements immediately following the cursor are being skipped in the results. This looks like to be caused by the Drizzle plugin incorrectly adding an offset of 1 to the query when cursor arguments are present.

### Reproduction
1. Execute a GraphQL query on either node query interface or any query returning a connection
2. Pass a cursor ID as an argument on the query for after / before 

I'm assuming that this is caused by this line:
https://github.com/hayes/pothos/blob/336f96e3b9a88375d5d15df16c8c7bebc0089058/packages/plugin-drizzle/src/utils/cursors.ts#L421

**Comment by hayes** [comment] 2024-12-27 05:15
Thanks for reporting this!

I think your right.  This looks like a remnant from porting some of this logic from prisma where cursors are inclusive. I'll try to confirm the root cause here, and get it fixed

**Comment by hayes** [comment] 2024-12-28 08:20
Should be fixed in the latest version

**Closed by hayes** 2024-12-28 08:20 UTC
