### ISSUE TITLE
combine prisma and federation plugins

### ISSUE THREAD

**Issue by JipSterk** [hayes/pothos#340] opened 2022-03-08 21:59 UTC
i want to use `prismaNode` on an object that is an external entity in a federated service.

if i try the following code snippit it throws an error saying it already has the typename registered

on the `pothos/plugin-federation` docs if i want to extend a entity i should use `externalRef`
but this returns a `ExternalEntityRef` with the type i want to extend but i can't use this in combination with `prismaNode`
from the `pothos/plugin-prisma` is this currently supported? or am i doing something wrong

```ts
builder
  .externalRef("User", builder.selection<Pick<User, "id">>("id"))
  .implement({
    externalFields: (t) => ({
      id: t.id(),
    }),
  });

const User = builder.prismaNode("User", {
  findUnique: (id) => ({ id }),
  id: {
    resolve: (user) => user.id,
  },
  fields: (t) => ({
    comments: t.relation("comments", {
      query: () => ({
        orderBy: {
          updatedAt: "desc",
        },
      }),
    }),
  }),
});

builder.asEntity(User, {
  key: builder.selection<Pick<User, "id">>("id"),
  resolveReference: ({ id }) => db.user.findFirst({ where: { id } }),
});
```

**Comment by hayes** [comment] 2022-03-08 22:33
Types should be defined either as an `externalRef` or as an entity, but not both.  I think if you just remove the extternalRef part it should work as expected.

**Comment by JipSterk** [comment] 2022-03-09 10:26
the generated schema i want to produce looks something like this:

`user-service`
```graphql
type User @key(fields: "id") {
  id: ID!
}
```

`comments-service`
```graphql
type User @extends @key(fields: "id") {
  id: ID! @external
  comments: [Comment!]!
}

type Comment @key(fields: "id") {
  id: ID!
  body: String!
}
```

currently i am missing the `@extends` directive on my `User` type as well as the `@external` on the `id` field on the  in the `comments-service`

so the schema for that would look like this:

```graphql
type User @key(fields: "id") {
  id: ID!
  comments: [Comment!]!
}

type Comment @key(fields: "id") {
  id: ID!
  body: String!
}
```

to add the missing decorators i should use the `builder.externalRef` and use `externalFields` on `implement`

like so: 

```ts
builder
  .externalRef("User", builder.selection<Pick<User, "id">>("id"))
  .implement({
    externalFields: (t) => ({
      id: t.id(),
    }),
  });
```

if i try to compose these schemas together in federation 2.0-beta it throws an error because there's already a `id` defined on the `User` type. to omit this error you woud need the `@external` decorator on `id` and the `@extends` on the `User` type

also in the `comments-service` i woud like to use a `prismaNode` for the user for loading the comments through a `relation` but when i use code like the following 

```ts
const User = builder.prismaNode("User", {
  findUnique: (id) => ({ id }),
  id: {
    resolve: (user) => user.id,
  },
  fields: (t) => ({
    comments: t.relation("comments", {
      query: () => ({
        orderBy: {
          updatedAt: "desc",
        },
      }),
    }),
  }),
});
```

`pothos` will throw an error saying it already has the `typename` of `User` registered

i hope this provides some context. if you want i can create a repository with a full code example

**Comment by hayes** [comment] 2022-03-09 22:03
Just spent some time trying to get create a working example for you, but the federation packages are currently a buggy mess.  The latest versions were all published with the wrong compiled code, so don't work at all.  Also ran into a few smaller bugs when I downgraded to the last correctly published version.

For now, I am not sure it's worth trying to use apollo federation.   If you want to keep trying to get this to work, here is a somewhat functional example (note pinned versions in the resolutions section of package.json) https://github.com/hayes/pothos/compare/mh-federation-example?expand=1

The main thing that does not work in this example is that it has an issue resolving users for some reason, the other relationships load correctly.  I haven't had time to track down the root cause of this, but I don't think it specific to pothos.

The other oddity here is that ID fields are converted to strings, so we need to assume that all id fields (keys) can be either an string when they are created via an external entity.

**Comment by hayes** [comment] 2022-03-10 01:18
opened up a couple issues (https://github.com/apollographql/federation/issues/1579, https://github.com/apollographql/federation/issues/1578) that would need to be resolved to get this working correctly.  The did quickly publish a fixed version that had the correct compiled code, so at least that issue is resolved.

I fixed the 2 issues above locally, and which seems to be sufficient to get the example I created working correctly.   The inconsistent ID issue isn't really anyone's fault, just something that is a bit inconvenient.  Apollo server (and some other implementations) will coerce ids (scalar id fields) in input types and arguments, which is generally a good thing.  It just means there is some extra casting that needs to be added in the revolvers.  If your keys/ids are already strings in your DB, this extra casting goes away.  I'll probably update the example to use string ids in the db, and set up Pothos to understand ids are always received as strings (it defaults to string | number because not all servers ensure that ids are always strings)

**Comment by hayes** [comment] 2022-03-10 01:29
Another thing I haven't gotten around to is figuring out how to integrate relay with the rest of the example.  Relay APIs are a little tricky in Federated schemas because the node/nodes fields need to know how to resolve all node types, and there isn't an easy way to do that automatically if your types are defined across several different schemas.  I know there are some projects that have experimented with this, but I am not familiar enough with federation to have a good understanding of how this should be implemented.

**Comment by JipSterk** [comment] 2022-03-10 15:35
thanks! for opening up these issues and looking into this so quickly.

i've edited my code to come closer to the result i desire.
i see that in the example you wrote you use a shared prisma database.
this is generally considered an anti-pattern but in the context it being an example its ok.

in my setup i use a database for each service.
and my schema in the `comments-service` looks the same.
the only problem i run in to is due to my structure and the way `@pothos/plugin-prisma` works
it want me to use either `builder.prismaObject` or `builder.prismaNode` for objects defined in `schema.primsa`
however if i do this it will throw an error with: `Error: Duplicate typename: Another type with name User already exists.`
is there any way that `builder.prismaObject` / `builder.prismaNode` and the `builder.externalRef` can coexist? 

many thanks in advance

**Comment by JipSterk** [comment] 2022-03-14 12:39
hi, i have setup a [example](https://github.com/JipSterk/pothos-federation-prisma-relay)
i hope this provides some context.

if you have questions on getting it up and running don't hesitate to hit me up.

**Comment by hayes** [comment] 2022-03-16 05:04
I'll try to a look on Thursday, sorry probably won't have time sooner than that

**Comment by hayes** [comment] 2022-03-18 21:08
@JipSterk Made a few simple changes that let the service start, and the gateway to merge the schemas successfully.  This also lets you create a user, and then load that user by ID.  The node and nodes queries don't work though, thats a relay/federation issue that's a little more complicated to solve.

**Comment by hayes** [comment] 2022-03-18 21:08
https://github.com/JipSterk/pothos-federation-prisma-relay/pull/1/files

**Comment by JipSterk** [comment] 2022-03-20 10:14
many thanks for the pull request and helping me out!
i don't know how i will resolve the issue of integrating relay into federated services.

**Comment by hayes** [comment] 2022-04-11 03:36
I've update the federation plugin to use the lastest version which includes some fixes I added to make federation work better with pothos and prisma.  That all seems to be working correctly now, so I am going to close this issue out.  Let me know if you have any luck with getting relay to work with federation.

**Closed by hayes** 2022-04-11 03:36 UTC
