### ISSUE TITLE
Multiple aliased subqueries generating N+1

### ISSUE THREAD

**Issue by juliobetta** [hayes/pothos#996] opened 2023-08-30 01:31 UTC
## Description:
When I execute a query with multiple aliased subqueries that point to the same table, it generates N+1 queries. The issue doesn't happen when I remove at least one of the other aliased subquery.

## Implementation

The query looks like the following:

```graphql
{
  account(id: 1) {
    values {
      edges {
        node {
          id
          value
          date
          currentScore: score(filter: {date: {equals: "2020-04-27"}})
          previousScore: score(filter: {date: {equals: "2019-04-27"}})
          currentScoreDate: scoreDate(filter: {date: {lte: "2020-07-30"}})
          previousScoreDate: scoreDate(filter: {date: {lte: "2019-07-30"}})
        }
      }
    }
  }
}
```

Here's the SQL log for the query above: 

```
Query: SELECT 1
Params: []
Query: SELECT "public"."Account"."id", "public"."Account"."name" FROM "public"."Account" WHERE ("public"."Account"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [1,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE (1=1 AND "public"."Value"."accountId" IN ($1)) ORDER BY "public"."Value"."id" ASC LIMIT $2 OFFSET $3
Params: [1,101,0]
Query: SELECT "public"."Score"."id", "public"."Score"."score", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" = $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3,$4,$5,$6,$7,$8,$9,$10,$11,$12)) ORDER BY "public"."Score"."score" DESC OFFSET $13
Params: ["2020-04-27 00:00:00 UTC","score3",1,2,3,4,5,6,7,8,9,10,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE "public"."Value"."id" IN ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) OFFSET $11
Params: [1,2,3,4,5,6,7,8,9,10,0]
Query: SELECT 1
Params: []
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [1,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."score", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" = $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3,$4,$5,$6,$7,$8,$9,$10,$11,$12)) ORDER BY "public"."Score"."score" DESC OFFSET $13
Params: ["2019-04-27 00:00:00 UTC","score3",1,2,3,4,5,6,7,8,9,10,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",1,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [2,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [2,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",2,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [1,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",2,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",1,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [4,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [3,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",3,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",4,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [3,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",3,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [5,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [6,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [5,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",5,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",6,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",5,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [4,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",4,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [8,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [8,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [9,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [7,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [7,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",8,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",8,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",7,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",7,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",9,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [6,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",6,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [10,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [10,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",10,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2020-07-30 00:00:00 UTC","score1",10,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE ("public"."Value"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [9,1,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3)) ORDER BY "public"."Score"."score" ASC LIMIT $4 OFFSET $5
Params: ["2019-07-30 00:00:00 UTC","score1",9,1,0]
```

If I comment `previousScoreDate` out for instance, it works as expected (no N+1):

```
Query: SELECT "public"."Account"."id", "public"."Account"."name" FROM "public"."Account" WHERE ("public"."Account"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
Params: [1,1,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE (1=1 AND "public"."Value"."accountId" IN ($1)) ORDER BY "public"."Value"."id" ASC LIMIT $2 OFFSET $3
Params: [1,101,0]
Query: SELECT "public"."Score"."id", "public"."Score"."score", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" = $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3,$4,$5,$6,$7,$8,$9,$10,$11,$12)) ORDER BY "public"."Score"."score" DESC OFFSET $13
Params: ["2020-04-27 00:00:00 UTC","score3",1,2,3,4,5,6,7,8,9,10,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE "public"."Value"."id" IN ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) OFFSET $11
Params: [1,2,3,4,5,6,7,8,9,10,0]
Query: SELECT "public"."Value"."id", "public"."Value"."value", "public"."Value"."date", "public"."Value"."accountId" FROM "public"."Value" WHERE "public"."Value"."id" IN ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) OFFSET $11
Params: [1,2,3,4,5,6,7,8,9,10,0]
Query: SELECT "public"."Score"."id", "public"."Score"."score", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" = $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3,$4,$5,$6,$7,$8,$9,$10,$11,$12)) ORDER BY "public"."Score"."score" DESC OFFSET $13
Params: ["2019-04-27 00:00:00 UTC","score3",1,2,3,4,5,6,7,8,9,10,0]
Query: SELECT "public"."Score"."id", "public"."Score"."date", "public"."Score"."valueId" FROM "public"."Score" WHERE (("public"."Score"."date" <= $1 AND "public"."Score"."name" = $2) AND "public"."Score"."valueId" IN ($3,$4,$5,$6,$7,$8,$9,$10,$11,$12)) ORDER BY "public"."Score"."score" ASC OFFSET $13
Params: ["2020-07-30 00:00:00 UTC","score1",1,2,3,4,5,6,7,8,9,10,0]
```

## How to reproduce
I just [created a PR](https://github.com/hayes/pothos-prisma-alias-bug/pull/2) in the alias bug repo.

## Library Version:
Pothos Core 3.33.0

```
"@pothos/core": "3.33.0",
"@pothos/plugin-add-graphql": "3.1.1",
"@pothos/plugin-errors": "3.11.1",
"@pothos/plugin-prisma": "3.58.0", // UPDATED VERSION 🙌
"@pothos/plugin-prisma-utils": "0.11.0",
"@pothos/plugin-relay": "3.43.1",
"@pothos/plugin-simple-objects": "3.7.0",
"@pothos/plugin-tracing": "0.5.8",
"@pothos/plugin-validation": "3.10.0",
"@prisma/client": "5.2.0"
"prisma": "5.2.0"
```

**Comment by hayes** [comment] 2023-08-30 03:07
So I think this is essentially the same bug, but on prismas side instead. 

The queries produced by Pothos here all look expected (even if it's not perfect).   The issue seems to be that Prisma isn't batching queries the way I would expect.

Pothos issues a bunch findUniqueOrThrow queries, which should be batched together grouping queries that have matching where clauses (excluding the id/unique piece).  

It seems like in this case, its not detecting that the where clauses are compatible for some reason

**Comment by juliobetta** [comment] 2023-08-30 03:43
Interesting... I'm not sure if that helps, but I had N+1 issues in the past with `findUniqueOrThrow` and had to replace it by `findUnique`.

**Comment by hayes** [comment] 2023-08-30 03:57
I fixed [that one](https://github.com/prisma/prisma-engines/pull/4019)!


and I think I've isolated the issue a bit more:

```ts
prisma.$use((params, next) => {
  console.dir(params, { depth: 6 });

  return next(params);
});

Promise.all([
  prisma.value.findUniqueOrThrow({
    where: {
      id: 1,
    },
    select: {
      scores: {
        where: {
          date: new Date('2020-04-27'),
        },
        take: 1,
      },
    },
  }),
  prisma.value.findUniqueOrThrow({
    where: {
      id: 3,
    },
    select: {
      scores: {
        where: {
          date: new Date('2020-04-27'),
        },
        take: 1,
      },
    },
  }),
  // Adding this query (note that the date is different) will de-optimize the query
  // prisma.value.findUniqueOrThrow({
  //   where: {
  //     id: 2,
  //   },
  //   select: {
  //     scores: {
  //       where: {
  //         date: new Date('2020-04-28'),
  //       },
  //       take: 1,
  //     },
  //   },
  // }),
]).then((res) => console.log(res));
```

```bash
Query: SELECT `main`.`Value`.`id` FROM `main`.`Value` WHERE `main`.`Value`.`id` IN (?,?) LIMIT ? OFFSET ?
Params: [1,3,-1,0]
Query: SELECT `main`.`Score`.`id`, `main`.`Score`.`score`, `main`.`Score`.`name`, `main`.`Score`.`date`, `main`.`Score`.`valueId` FROM `main`.`Score` WHERE (`main`.`Score`.`date` = ? AND `main`.`Score`.`valueId` IN (?,?)) ORDER BY `main`.`Score`.`id` ASC LIMIT ? OFFSET ?
Params: ["2020-04-27 00:00:00 UTC",1,3,-1,0]
[ { scores: [] }, { scores: [] } ]
```

with multiple dates:
```bash
Query: SELECT `main`.`Value`.`id` FROM `main`.`Value` WHERE (`main`.`Value`.`id` = ? AND 1=1) LIMIT ? OFFSET ?
Params: [2,1,0]
Query: SELECT `main`.`Value`.`id` FROM `main`.`Value` WHERE (`main`.`Value`.`id` = ? AND 1=1) LIMIT ? OFFSET ?
Params: [1,1,0]
Query: SELECT `main`.`Value`.`id` FROM `main`.`Value` WHERE (`main`.`Value`.`id` = ? AND 1=1) LIMIT ? OFFSET ?
Params: [3,1,0]
Query: SELECT `main`.`Score`.`id`, `main`.`Score`.`score`, `main`.`Score`.`name`, `main`.`Score`.`date`, `main`.`Score`.`valueId` FROM `main`.`Score` WHERE (`main`.`Score`.`date` = ? AND `main`.`Score`.`valueId` IN (?)) ORDER BY `main`.`Score`.`id` ASC LIMIT ? OFFSET ?
Params: ["2020-04-27 00:00:00 UTC",1,1,0]
Query: SELECT `main`.`Score`.`id`, `main`.`Score`.`score`, `main`.`Score`.`name`, `main`.`Score`.`date`, `main`.`Score`.`valueId` FROM `main`.`Score` WHERE (`main`.`Score`.`date` = ? AND `main`.`Score`.`valueId` IN (?)) ORDER BY `main`.`Score`.`id` ASC LIMIT ? OFFSET ?
Params: ["2020-04-28 00:00:00 UTC",2,1,0]
Query: SELECT `main`.`Score`.`id`, `main`.`Score`.`score`, `main`.`Score`.`name`, `main`.`Score`.`date`, `main`.`Score`.`valueId` FROM `main`.`Score` WHERE (`main`.`Score`.`date` = ? AND `main`.`Score`.`valueId` IN (?)) ORDER BY `main`.`Score`.`id` ASC LIMIT ? OFFSET ?
Params: ["2020-04-27 00:00:00 UTC",3,1,0]
[ { scores: [] }, { scores: [] }, { scores: [] } ]
```

**Comment by hayes** [comment] 2023-08-30 04:07
Not sure how closely you've looked at what Pothos is doing under the hood to make these queries work but, basically what id does is:

* Combine as much into the initial query as possible
* For any field that couldn't be included in the initial query (usually this is because the same field is queried with different constraints as you are doing here), it will re-select the parent, and select the relation, this also batches other siblings that couldn't initially be loaded.

In this case, the initial query looks something like:

```ts
{
  args: {
    include: {
      values: {
        where: {},
        take: 101,
        skip: 0,
        include: {
          scores: {
            orderBy: { score: 'desc' },
            take: 1,
            where: { date: [Object: null prototype], name: 'score3' },
            select: { score: true }
          }
        }
      }
    },
    where: { id: 1 }
  },
  dataPath: [],
  runInTransaction: false,
  action: 'findUnique',
  model: 'Account'
}
```

followed by queries like:

```ts
{
  args: {
    include: {
      scores: {
        orderBy: { score: 'desc' },
        take: 1,
        where: {
          date: [Object: null prototype] { equals: 2019-04-27T00:00:00.000Z },
          name: 'score3'
        },
        select: { score: true }
      }
    },
    where: { id: 1 }
  },
  dataPath: [],
  runInTransaction: false,
  action: 'findUniqueOrThrow',
  model: 'Value'
}
{
  args: {
    include: {
      scores: {
        orderBy: { score: 'asc' },
        take: 1,
        where: {
          date: [Object: null prototype] { lte: 2020-07-30T00:00:00.000Z },
          name: 'score1'
        },
        select: { date: true }
      }
    },
    where: { id: 1 }
  },
  dataPath: [],
  runInTransaction: false,
  action: 'findUniqueOrThrow',
  model: 'Value'
}
```

It seems that prisma will only do batching when all queries can be batched into one (can't do multiple batches for the same model at the same time).

This is not a limitation I had been aware of before this...

I'm not sure if this is something they could easily fix upsteam...

**Comment by juliobetta** [comment] 2023-08-30 04:19
Thanks for going into detail on this! 
I couldn't reproduce on our testing repo, but in my project, the N+1 issue didn't happen when I downgraded to prisma v4.16.2 🤷‍♂️

**Comment by hayes** [comment] 2023-09-01 06:03
I tracked down the batching logic in prisma: https://github.com/prisma/prisma-engines/blob/main/query-engine/core/src/query_document/mod.rs#L103-L110

It's fairly naive, the client sends all queries to the engine in a batch that occur in the same tick,  then the engine will batch them only if all queries in the batch can easily be converted from a findUnique to a findMany, which fully explains the behavior above.

I have an idea about how to work around this in Pothos, but it requires a more complex change.

Currently pothos loads as much as it can in the initial query, but any field that isn't part of the initial query more or less resolves it's dependencies in isolation.  For the n+1 case this means for each item in a list, it will compute the same query and then attempt to load it with a prisma `findUniqueOrThrow`, hoping that prisma batches them.  If all the queries are the same, this works great, but as you discovered, if there are conflicting queries issued in the same tick/batch this doesn't work.

What pothos could do is create a cache + schedular that has some nice benefits. 

For a query like:

```graphql
query {
  user {
    posts {
      comments1: comments(order: Asc) {
        title
      }
      comments2: comments(order: Desc) {
        title
      }
    }
}
```
Imagine you have 5 posts, with the comments2 selection not fulfilled by the initial query.  Pothos currently traverses the same selection sets to build up the same query for each post in the list.  If resolving the prisma query is handled through a caching request schedular, pothos can avoid having to recalculate queries.  By creating shared state for these lookups it also moves the detection of conflicting queries into that shared state, and would allow a schedular to queue conflicting queries so they aren't issued on the same tick, preventing prisma from batching incompatible queries which prevents the n+1 queries.


Not sure if/when I'll have time to actually make this change, but I think the implementation is actually pretty straight forward.

**Comment by hayes** [comment] 2023-09-01 16:00
started working on this here: https://github.com/hayes/pothos/pull/1003

**Comment by hayes** [comment] 2023-09-01 17:22
New version with this change should be published now, let me know if that resolves your issue

**Closed by hayes** 2023-09-01 17:22 UTC

**Comment by juliobetta** [comment] 2023-09-02 01:14
awesome dude! just tested it and it works 💯 . great job, thank you 🎉

**Comment by hayes** [comment] 2023-09-02 01:17
No problem

**Comment by juliobetta** [comment] 2023-09-05 18:46
just FYI, I'm having issues with my tests (with vitest) getting cancelled due to `timeout` with queries like this:

```gql
{
  values {
    id
    date
  }
  filteredValues: values(filter: { date: { lte: "..." } }) {
    id
    date
  }
}
```

could it be something related to the [`tick` interval](https://github.com/hayes/pothos/blob/82a9c07b27c46dadd583021d9b0b69b961873e12/packages/plugin-prisma/src/model-loader.ts#L37) introduced in v3.59.0? It doesn't happen in v3.58.0. I'm still trying to reproduce the issue in the example project...  🫠 I'll keep you posted.

**Comment by hayes** [comment] 2023-09-05 18:53
It's possible, although I'm not sure why this change would cause timeouts.  If you can share a way to reproduce it, I'll get it fixed.  Are you mocking any of the Prisma calls in your tests?

**Comment by hayes** [comment] 2023-09-05 18:55
Or maybe mocking setTimeout?

**Comment by juliobetta** [comment] 2023-09-05 22:27
oh man, you're right! `vi.useFakeTimers()`. my bad... 🤦‍♂️
