### ISSUE TITLE
@pothos/core cannot be used as an ESM module

### ISSUE THREAD

**Issue by barryhagan** [hayes/pothos#633] opened 2022-10-21 02:01 UTC
Attempting to use @pothos/core in an ESM project will cause typescript errors.  It looks like this is because the generated types in /esm are using relative imports for some function return types.  I'm not sure if you could avoid this by adding explicit return types from imports, or if the esm-transformer must be updated.

For example, in ./esm/config-store.d.ts:
```
    getTypeConfig<T extends PothosTypeConfig["kind"]>(ref: ConfigurableRef<Types> | string, kind?: T): Extract<import("./types").PothosEnumTypeConfig, {
        kind: T;
    }> | Extract<import("./types").PothosInputObjectTypeConfig, {
        kind: T;
    }> | Extract<import("./types").PothosInterfaceTypeConfig, {
        kind: T;
    }> | Extract<import("./types").PothosMutationTypeConfig, {
        kind: T;
    }> | Extract<PothosObjectTypeConfig, {
        kind: T;
    }> | Extract<import("./types").PothosQueryTypeConfig, {
        kind: T;
    }> | Extract<import("./types").PothosScalarTypeConfig, {
        kind: T;
    }> | Extract<import("./types").PothosSubscriptionTypeConfig, {
        kind: T;
    }> | Extract<import("./types").PothosUnionTypeConfig, {
        kind: T;
    }>;
```

This is the summary list of errors:
```
Errors  Files
     8  ../../packages/core/esm/config-store.d.ts:26
    11  ../../packages/core/esm/fieldUtils/builder.d.ts:11
    40  ../../packages/core/esm/fieldUtils/input.d.ts:14
    11  ../../packages/core/esm/fieldUtils/root.d.ts:12
```

**Repro**

1) In the simple-classes example project (./examples/simple-classes), update the package.json and tsconfig.json to build as ESM:

In package.json, add:
`"type":"module",`

In tsconfig.json, change:
` "moduleResolution": "Node16",`

2) run `pnpm type` in this example project.  Once it is compiling as ESM, the errors will throw.

**Comment by hayes** [comment] 2022-10-21 02:18
Looks like there was a regression in the build script, I think something intended for debugging got checked in on accident (it was only applying the transform for dynamic imports to index files for some reason). 

Just pushed a fix, it's building now, and should be released in a few minutes

**Comment by hayes** [comment] 2022-10-21 02:19
let me know if you have any more issues after updating

**Comment by barryhagan** [comment] 2022-10-21 03:05
Thanks for the quick response. I pulled 3.22.7 and some errors have been fixed, but there are other issues in these two output files, all related to imports without path+extension, e.g.: ` import("../types").BaseEnum ? import("../types").ValuesFromEnum<T>`

```
Errors  Files
    26  @pothos+core@3.22.7_graphql@16.6.0/node_modules/@pothos/core/esm/fieldUtils/builder.d.ts:11
    26  @pothos+core@3.22.7_graphql@16.6.0/node_modules/@pothos/core/esm/fieldUtils/root.d.ts:12
```

**Comment by hayes** [comment] 2022-10-21 03:32
Interesting, looks like a few imports aren't picked up properly by the transform.  I'll take a look later tonight

**Comment by hayes** [comment] 2022-10-21 06:11
okay, fixed another issue with the esm transform.  Hopefully this time it works for ya

**Closed by hayes** 2022-10-21 06:11 UTC

**Comment by barryhagan** [comment] 2022-10-21 11:42
Looking good with 3.22.8.  Thanks for the fix.
