### ISSUE TITLE
Unable to add fields to connection

### ISSUE THREAD

**Issue by Jomik** [hayes/pothos#268] opened 2022-01-20 08:39 UTC
I am trying to resolve fields in the second argument of `t.connection`, but it is unable to see the extra fields that I add in my resolver. TypeScript seems to throw away this information.

I get `Argument of type 'string' is not assignable to parameter of type 'never'.` on the `'count'` literal in my expose.
```ts
builder.objectField(Viewer, 'assignedTickets', (t) =>
  t.connection(
    {
      type: Ticket,
      nullable: true,
      args: {
        orderBy: t.arg({
          type: [TicketsOrderBy],
          defaultValue: [
            { priority: 'Ascending' },
            { createdDate: 'Descending' },
          ],
        }),
        status: t.arg({
          type: [AssignedTicketsStatusInput],
          defaultValue: ['InProgress'],
        }),
        priorities: t.arg({
          type: [TicketsPriorityInput],
        }),
      },
      resolve: async (parent, args, { tickets }) => {
        let count = 0;
        const result = await resolveOffsetConnection(
          { args },
          async ({ offset, limit }) => {
            const { status, orderBy, priorities } = args;

            const { data } = await tickets.ticketsGetAllV2({
              skip: offset,
              limit,
              assignedTo: parent.id,
              status: status ?? undefined,
              sort: mapOrderByToMiddlewareFormat(orderBy),
              priority: mapPrioritiesInputToMiddleware(priorities),
            });
            count = data.count;

            return data.results.map(ticketMapper);
          }
        );

        return result && { count, ...result };
      },
    },
    {
      fields: (t) => ({
        count: t.exposeInt('count'),
      }),
    }
  )
);
```

Currently I work around it by creating a `ConnectionObject` and explicitly type it.
```ts
type ConnectionObjectResolveShape<
  T,
  Extras extends Record<string, any>
> = ConnectionShape<
  SchemaTypes,
  NonNullable<ParentShape<SchemaTypes, T>>,
  boolean
> &
  Extras;

const TicketsConnection = builder.connectionObject<
  typeof Ticket,
  ConnectionObjectResolveShape<typeof Ticket, { count: number }>
>({
  type: Ticket,
  name: 'TicketsConnection',
  fields: (t) => ({
    count: t.exposeInt('count'),
  }),
});
```

**Comment by hayes** [comment] 2022-01-20 18:32
Looks like there is some sort of type issue caused by result being nullable.  I can't fix it imideatly because I am in the middle of some big changes and I don't want to cause more conflicts until its done, but the easy work around for now is to `return { count, ...result! }`  result does not look like its actually nullable there, its just nullable because of how the helper is typed.

**Comment by hayes** [comment] 2022-01-25 20:19
Fix for this is merged, should be published in the next couple minutes

**Closed by hayes** 2022-01-25 20:19 UTC
